# Generated by Django 2.0.4 on 2018-05-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180516_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestpic',
            options={'managed': False},
        ),
    ]
