# Generated by Django 2.0.4 on 2018-05-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('netflix', models.CharField(max_length=200)),
                ('hulu', models.CharField(max_length=200)),
                ('hbo', models.CharField(max_length=200)),
                ('amazonprime', models.CharField(max_length=200)),
            ],
        ),
    ]
